### ISSUE TITLE
Componente Tag

### ISSUE THREAD

**Issue by KathiaNeira** [frontend-labs/frontendlabs-ui#3]
Se requiere la creación del componente Tag para los temas existentes:

- Jade
- Javascript
- Nodejs
- Stylus
- React
- Angular
- Css
- Html
- Pug
- Vue
- Typescript
- Ruby
- Linux

Estos son algunos tag iniciales, luego se irán agregando más dependiendo de los temas que veamos más adelante.

**Comment by wilsson** [comment]
:+1:
